### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by newswim** [techmill/techmill-slack#3]
reference material:

http://phillydev.org/
https://www.djangoproject.com/conduct/

http://adainitiative.org/2014/02/18/howto-design-a-code-of-conduct-for-your-community/

**Comment by kyletaylored** [comment]
Added a mix between Phillydev and Django. Added a sub-page at /coc for strictly Code of Conduct. The Slackin heroku app now let's you designate a Code of Conduct page people must agree to before signing up for the group.
